// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package database

import (
	"database/sql"
)

type Gallery struct {
	ID            int64
	Name          string
	Description   sql.NullString
	Imagelocation sql.NullString
}
