// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: query.sql

package database

import (
	"context"
)

const getGalleries = `-- name: GetGalleries :many
SELECT id, name, description, imagelocation FROM Galleries
`

func (q *Queries) GetGalleries(ctx context.Context) ([]Gallery, error) {
	rows, err := q.db.QueryContext(ctx, getGalleries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gallery
	for rows.Next() {
		var i Gallery
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Imagelocation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
