// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type Contact struct {
	Name    string `json:"name"`
	Email   string `json:"email"`
	Message string `json:"message"`
}

type ContactResult struct {
	Sent *bool `json:"sent"`
}

type NewGallery struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	File        graphql.Upload `json:"file"`
}
